// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StravaSegmentsPerformanceBackend.Data;

#nullable disable

namespace StravaSegmentsPerformanceBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903210806_WipeAllData")]
    partial class WipeAllData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StravaSegmentsPerformanceBackend.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DetailsFetched")
                        .HasColumnType("boolean");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<int>("ElapsedTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovingTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SportType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("StravaActivityId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "StravaActivityId")
                        .IsUnique();

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("StravaSegmentsPerformanceBackend.Models.SegmentEffort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<double?>("AverageHeartRate")
                        .HasColumnType("double precision");

                    b.Property<int>("ElapsedTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("SegmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("StravaSegmentEffortId")
                        .HasColumnType("bigint");

                    b.Property<long>("StravaSegmentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StravaSegmentEffortId")
                        .IsUnique();

                    b.ToTable("SegmentEfforts");
                });

            modelBuilder.Entity("StravaSegmentsPerformanceBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("StravaAthleteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StravaAthleteId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StravaSegmentsPerformanceBackend.Models.WorkoutFetchStatus", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ActivitiesProcessed")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("Stage")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalToProcess")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("WorkoutFetchStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
